name: Check One Piece Chapter

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run chapter notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python chapter_notifier.py

      - name: Commit updated snapshot
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add last_chapter.txt
          git commit -m "Update last_chapter.txt [bot]" || echo "No changes to commit"
          git push
